Uncaught TypeError: users?.find is not a function
    at getUserName (cab-dashboard.tsx:294:25)
    at cab-dashboard.tsx:676:59
    at Array.map (<anonymous>)
    at CABDashboard (cab-dashboard.tsx:653:25)
    at renderWithHooks (chunk-RPCDYKBN.js?v=83533dd4:11548:26)
    at updateFunctionComponent (chunk-RPCDYKBN.js?v=83533dd4:14582:28)
    at beginWork (chunk-RPCDYKBN.js?v=83533dd4:15924:22)
    at HTMLUnknownElement.callCallback2 (chunk-RPCDYKBN.js?v=83533dd4:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-RPCDYKBN.js?v=83533dd4:3699:24)
    at invokeGuardedCallback (chunk-RPCDYKBN.js?v=83533dd4:3733:39)
chunk-RPCDYKBN.js?v=83533dd4:14032 The above error occurred in the <CABDashboard> component:

    at CABDashboard (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/src/pages/cab-dashboard.tsx:33:47)
    at main
    at div
    at div
    at AuthenticatedLayout (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/src/App.tsx:62:32)
    at ProtectedRoute (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/src/components/auth/protected-route.tsx:76:3)
    at Route (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=27186edc:206:16)
    at Switch (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=27186edc:262:17)
    at Router (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/wouter.js?v=27186edc:161:17)
    at AuthProvider (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/src/components/auth/protected-route.tsx:36:32)
    at QueryClientProvider (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js?v=809ff670:2933:3)
    at App (https://4d1866ca-f8aa-4963-b885-eb39eba87996-00-49gdot7a8ij5.sisko.replit.dev/src/App.tsx:102:49)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-RPCDYKBN.js?v=83533dd4:14032
chunk-RPCDYKBN.js?v=83533dd4:9129 Uncaught TypeError: users?.find is not a function
    at getUserName (cab-dashboard.tsx:294:25)
    at cab-dashboard.tsx:676:59
    at Array.map (<anonymous>)
    at CABDashboard (cab-dashboard.tsx:653:25)
    at renderWithHooks (chunk-RPCDYKBN.js?v=83533dd4:11548:26)
    at updateFunctionComponent (chunk-RPCDYKBN.js?v=83533dd4:14582:28)
    at beginWork (chunk-RPCDYKBN.js?v=83533dd4:15924:22)
    at beginWork$1 (chunk-RPCDYKBN.js?v=83533dd4:19753:22)
    at performUnitOfWork (chunk-RPCDYKBN.js?v=83533dd4:19198:20)
    at workLoopSync (chunk-RPCDYKBN.js?v=83533dd4:19137:13)